Revert "Hackedly upgrade psycopg2 so we can see if that stops the deadlocks"
This caused lots of
```
[2016-09-20 08:42:48,926: INFO/Worker-7] Traceback (most recent call last):
  File "/aleph/aleph/ingest/__init__.py", line 36, in ingest_url
    meta = get_archive().archive_file(tmp_path, meta, move=True)
  File "/aleph/aleph/core.py", line 128, in get_archive
    app = current_app._get_current_object()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
      raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
```
This reverts commit 48d1ba380c7eed1aa617ce48efe47795f39027f6.